CREATE DATABASE airflow;

CREATE USER airflow WITH ENCRYPTED PASSWORD 'airflow';
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;

\c airflow;
GRANT ALL ON SCHEMA public TO airflow;
GRANT CREATE ON SCHEMA public TO airflow;