- Documentation:
    - n8n:
        - href: https://docs.n8n.io/
          icon: n8n.png
    - Airflow:
        - href: https://airflow.apache.org/docs/apache-airflow/stable/index.html
          icon: apache-airflow.png
    - MLflow:
        - href: https://mlflow.org/docs/latest/ml/
          icon: si-mlflow
    - Jupyter:
        - href: https://jupyterlab.readthedocs.io/en/latest/
          icon: jupyter.png
    - PostgreSQL:
        - href: hhttps://www.postgresql.org/docs/current/
          icon: postgresql.png
    - homepage:
        - href: https://gethomepage.dev/
          icon: si-homepage

- ML Resources:
    - Kaggle:
        - href: https://kaggle.com
          icon: si-kaggle
    - Hugging Face:
        - href: https://huggingface.co
          icon: si-huggingface

- Developer Resources:
    - GitHub:
        - href: https://github.com
          icon: si-github